CREATE TABLE IF NOT EXISTS aida_tbl_EventReceipt (
  uidCall CHAR(36) NOT NULL,
  eventKey VARCHAR(160) NOT NULL,
  dtCreated DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (uidCall,eventKey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
